-module(windsurf_demo_handler).
-behavior(cowboy_handler).

-export([init/2]).

init(Req0, State) ->
    Html =
        <<
            "<!DOCTYPE html>\n"
            "<html>\n"
            "    <head>\n"
            "        <meta charset=\"UTF-8\">\n"
            "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
            "        <title>Windsurf Demo Chat</title>\n"
            "        <style>\n"
            "            :root {\n"
            "                --color-primary: #10b981;\n"
            "                --color-primary-dark: #059669;\n"
            "                --color-primary-light: #d1fae5;\n"
            "                --color-gray: #374151;\n"
            "                --color-gray-light: #f3f4f6;\n"
            "            }\n"
            "            \n"
            "            body {\n"
            "                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;\n"
            "                margin: 0;\n"
            "                padding: 10px;\n"
            "                background: var(--color-gray-light);\n"
            "                color: var(--color-gray);\n"
            "                height: 100vh;\n"
            "                display: flex;\n"
            "                flex-direction: column;\n"
            "            }\n"
            "\n"
            "            .container {\n"
            "                max-width: 600px;\n"
            "                margin: 0 auto;\n"
            "                width: 100%;\n"
            "                background: white;\n"
            "                border-radius: 8px;\n"
            "                box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n"
            "                padding: 12px;\n"
            "                flex-grow: 1;\n"
            "                display: flex;\n"
            "                flex-direction: column;\n"
            "            }\n"
            "\n"
            "            h1 {\n"
            "                text-align: center;\n"
            "                color: var(--color-primary-dark);\n"
            "                margin: 0.5rem 0;\n"
            "                font-size: 1.5rem;\n"
            "                font-weight: 600;\n"
            "            }\n"
            "\n"
            "            #username-container {\n"
            "                display: flex;\n"
            "                align-items: center;\n"
            "                gap: 0.5rem;\n"
            "                padding: 0.75rem;\n"
            "                background: var(--color-primary-light);\n"
            "                border-radius: 6px;\n"
            "                margin-bottom: 0.75rem;\n"
            "            }\n"
            "\n"
            "            #messages {\n"
            "                flex-grow: 1;\n"
            "                overflow-y: auto;\n"
            "                padding: 0.5rem;\n"
            "                margin-bottom: 0.75rem;\n"
            "                border: 1px solid #e5e7eb;\n"
            "                border-radius: 6px;\n"
            "                background: #ffffff;\n"
            "            }\n"
            "\n"
            "            #input-container {\n"
            "                display: none;\n"
            "                gap: 0.5rem;\n"
            "                margin-top: auto;\n"
            "            }\n"
            "\n"
            "            input[type='text'] {\n"
            "                flex-grow: 1;\n"
            "                padding: 0.5rem 0.75rem;\n"
            "                border: 1.5px solid #e5e7eb;\n"
            "                border-radius: 4px;\n"
            "                font-size: 0.875rem;\n"
            "                transition: border-color 0.2s;\n"
            "            }\n"
            "\n"
            "            input[type='text']:focus {\n"
            "                outline: none;\n"
            "                border-color: var(--color-primary);\n"
            "                box-shadow: 0 0 0 2px var(--color-primary-light);\n"
            "            }\n"
            "\n"
            "            button {\n"
            "                padding: 0.5rem 1rem;\n"
            "                background: var(--color-primary);\n"
            "                color: white;\n"
            "                border: none;\n"
            "                border-radius: 4px;\n"
            "                font-weight: 500;\n"
            "                font-size: 0.875rem;\n"
            "                cursor: pointer;\n"
            "                transition: background-color 0.2s;\n"
            "            }\n"
            "\n"
            "            button:hover {\n"
            "                background: var(--color-primary-dark);\n"
            "            }\n"
            "\n"
            "            .message {\n"
            "                margin: 0.25rem 0;\n"
            "                padding: 0.5rem 0.75rem;\n"
            "                border-radius: 6px;\n"
            "                max-width: 85%;\n"
            "                word-wrap: break-word;\n"
            "                font-size: 0.875rem;\n"
            "            }\n"
            "\n"
            "            .message.system {\n"
            "                background: #f3f4f6;\n"
            "                color: #6b7280;\n"
            "                text-align: center;\n"
            "                max-width: 100%;\n"
            "                font-style: italic;\n"
            "                font-size: 0.75rem;\n"
            "                padding: 0.25rem 0.5rem;\n"
            "                margin: 0.25rem 0;\n"
            "            }\n"
            "\n"
            "            .message.self {\n"
            "                background: var(--color-primary);\n"
            "                color: white;\n"
            "                margin-left: auto;\n"
            "                border-bottom-right-radius: 2px;\n"
            "            }\n"
            "\n"
            "            .message.other {\n"
            "                background: var(--color-gray-light);\n"
            "                color: var(--color-gray);\n"
            "                margin-right: auto;\n"
            "                border-bottom-left-radius: 2px;\n"
            "            }\n"
            "\n"
            "            .username {\n"
            "                font-size: 0.75rem;\n"
            "                margin-bottom: 0.125rem;\n"
            "                font-weight: 600;\n"
            "            }\n"
            "\n"
            "            .message.self .username {\n"
            "                color: rgba(255, 255, 255, 0.9);\n"
            "            }\n"
            "\n"
            "            .message.other .username {\n"
            "                color: var(--color-primary-dark);\n"
            "            }\n"
            "\n"
            "            @media (max-width: 640px) {\n"
            "                body {\n"
            "                    padding: 8px;\n"
            "                }\n"
            "\n"
            "                .container {\n"
            "                    border-radius: 6px;\n"
            "                    padding: 8px;\n"
            "                }\n"
            "\n"
            "                .message {\n"
            "                    max-width: 90%;\n"
            "                }\n"
            "            }\n"
            "        </style>\n"
            "    </head>\n"
            "    <body>\n"
            "        <div class=\"container\">\n"
            "            <h1>Windsurf Chat</h1>\n"
            "            <div id=\"username-container\">\n"
            "                <input type=\"text\" id=\"username-input\" placeholder=\"Enter your username\" autofocus>\n"
            "                <button onclick=\"setUsername()\">Join Chat</button>\n"
            "            </div>\n"
            "            <div id=\"messages\"></div>\n"
            "            <div id=\"input-container\">\n"
            "                <input type=\"text\" id=\"message-input\" placeholder=\"Type your message...\" onkeypress=\"if(event.key === 'Enter') sendMessage()\">\n"
            "                <button onclick=\"sendMessage()\">Send</button>\n"
            "            </div>\n"
            "        </div>\n"
            "        <script>\n"
            "            let ws = null;\n"
            "            let username = '';\n"
            "            \n"
            "            function setUsername() {\n"
            "                const input = document.getElementById('username-input');\n"
            "                const inputUsername = input.value.trim();\n"
            "                if (inputUsername) {\n"
            "                    username = inputUsername;\n"
            "                    document.getElementById('username-container').style.display = 'none';\n"
            "                    document.getElementById('input-container').style.display = 'flex';\n"
            "                    connectWebSocket(username);\n"
            "                } else {\n"
            "                    alert('Please enter a username');\n"
            "                }\n"
            "            }\n"
            "            \n"
            "            function connectWebSocket(username) {\n"
            "                const wsUrl = new URL('/websocket', window.location.href);\n"
            "                wsUrl.protocol = wsUrl.protocol.replace('http', 'ws');\n"
            "                wsUrl.searchParams.append('username', username);\n"
            "                console.log('Connecting with URL:', wsUrl.href);\n"
            "                ws = new WebSocket(wsUrl.href);\n"
            "                \n"
            "                ws.onopen = function() {\n"
            "                    console.log('Connected to WebSocket with username:', username);\n"
            "                    addSystemMessage('Connected to chat as: ' + username);\n"
            "                };\n"
            "                \n"
            "                ws.onclose = function() {\n"
            "                    console.log('Disconnected from WebSocket');\n"
            "                    addSystemMessage('Disconnected from chat');\n"
            "                };\n"
            "                \n"
            "                ws.onmessage = function(event) {\n"
            "                    const data = JSON.parse(event.data);\n"
            "                    addMessage(data.message, data.username, username === data.username);\n"
            "                };\n"
            "            }\n"
            "            \n"
            "            function sendMessage() {\n"
            "                const input = document.getElementById('message-input');\n"
            "                const message = input.value.trim();\n"
            "                if (message && ws && ws.readyState === WebSocket.OPEN) {\n"
            "                    ws.send(message);\n"
            "                    input.value = '';\n"
            "                }\n"
            "            }\n"
            "            \n"
            "            function addMessage(message, msgUsername, isSelf) {\n"
            "                const messagesDiv = document.getElementById('messages');\n"
            "                const messageDiv = document.createElement('div');\n"
            "                messageDiv.className = `message ${isSelf ? 'self' : 'other'}`;\n"
            "                \n"
            "                const usernameDiv = document.createElement('div');\n"
            "                usernameDiv.className = 'username';\n"
            "                usernameDiv.textContent = msgUsername;\n"
            "                \n"
            "                const messageContent = document.createElement('div');\n"
            "                messageContent.className = 'message-content';\n"
            "                messageContent.textContent = message;\n"
            "                \n"
            "                messageDiv.appendChild(usernameDiv);\n"
            "                messageDiv.appendChild(messageContent);\n"
            "                messagesDiv.appendChild(messageDiv);\n"
            "                messagesDiv.scrollTop = messagesDiv.scrollHeight;\n"
            "            }\n"
            "            \n"
            "            function addSystemMessage(message) {\n"
            "                const messagesDiv = document.getElementById('messages');\n"
            "                const messageDiv = document.createElement('div');\n"
            "                messageDiv.className = 'message system';\n"
            "                messageDiv.textContent = message;\n"
            "                messagesDiv.appendChild(messageDiv);\n"
            "                messagesDiv.scrollTop = messagesDiv.scrollHeight;\n"
            "            }\n"
            "\n"
            "            document.getElementById('username-input').addEventListener('keypress', function(e) {\n"
            "                if (e.key === 'Enter') {\n"
            "                    setUsername();\n"
            "                }\n"
            "            });\n"
            "        </script>\n"
            "    </body>\n"
            "</html>"
        >>,
    {ok,
        cowboy_req:reply(
            200,
            #{<<"content-type">> => <<"text/html">>},
            Html,
            Req0
        ),
        State}.
